# Default values for voting-app

vote:
  replicaCount: 1
  image:
    repository: sganadicontainercicd.azurecr.io/votingapp
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 31000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

result:
  replicaCount: 1
  image:
    repository: sganadicontainercicd.azurecr.io/resultapp
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 31001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

worker:
  replicaCount: 1
  image:
    repository: sganadicontainercicd.azurecr.io/workerapp
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "alpine"
  service:
    port: 6379
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

db:
  replicaCount: 1
  image:
    repository: postgres
    tag: "15-alpine"
  service:
    port: 5432
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

imagePullSecrets:
  - name: acr-secret
